# Generated by Django 4.0.2 on 2022-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_homeabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Rotary Nickel Screen', 'Rotary Nickel Screen'), ('Flat Bed Screen', 'Flat Bed Screen'), ('Reactive Dyes', 'Reactive Dyes'), ('Auxiliaries', 'Auxiliaries'), ('Others', 'Others')], max_length=100),
        ),
    ]
